version: '3'

services:
  lamp:
    image: mattrayner/lamp:latest-1804
    env_file: .env
    environment: 
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    networks:
      - webproxy
    expose:
      - "80"
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./mysql:/var/lib/mysql

networks:
  webproxy:
    external: true